name: GitHub Metrics
on:
  schedule:
    # Runs every day at midnight
    - cron: '* */24 * * *'
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: mrshakils
          output_action: "commit"
          filename: github-metrics.svg
          template: classic
          base: activity, community, repositories
          
          plugin_isocalendar: yes
