name: Generate Snake Animation

on:
  # Run this workflow every 12 hours
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          color_snake: '#A277FF'
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'docs: update snake color'
          add: 'dist'
